### PR TITLE
Part of CC-1391: Figure out why CI tests end early for Kotlin (SQLite)

### PR DESCRIPTION
**Pull request by andy1li**
Need to log out why SDK failed to download the tester artifact.

### CODE REVIEW

**Comment by rohitpaulk** [comment]
@andy1li are you able to reliably trigger this error? I thought that exceptions from async functions are automatically bubbled up anyway 🤔

**Comment by andy1li** [comment]
@rohitpaulk TBH, I'm not sure. That's why I'm trying to log it out, in order to be sure.

The fact that the CI just silently stopped is beyond me right now.

**Review by rohitpaulk — APPROVED** [review]

**Comment by rohitpaulk** [comment]
Cool. Would recommend trying to replicate this - you can create a test repo and have that build a branch of `course-sdk`. Would be faster than waiting for PR reviews etc.

**Comment by andy1li** [comment]
Probably not in the right direction.

**Pull request closed without merging**
